import React, { useEffect, useMemo, useState } from "react";
import { BarChart, Bar, LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from "recharts";
import { AlertTriangle, ArrowRight, BarChart3, CheckCircle2, IndianRupee, Users, WalletCards } from "lucide-react";
const empty={rows:[],meta:{}};
async function load(name){const r=await fetch(`/data/${name}.json`);if(!r.ok)throw Error(`Missing ${name}.json`);return r.json()}
const money=n=>n==null?"—":new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(n));
const number=n=>n==null?"—":new Intl.NumberFormat("en-IN").format(Number(n));
function Section({title,period,children}){return <section className="section"><div className="section-head"><div><h2>{title}</h2><div className="period">{period}</div></div></div>{children}</section>}
function Empty({text="Run the matching BigQuery query and export its result as JSON."}){return <div className="empty"><AlertTriangle size={18}/><span>{text}</span></div>}
function App(){
 const [tab,setTab]=useState("performance"); const [data,setData]=useState({channels:empty,funnel:empty,revenue_monthly:empty,daily_trend:empty,retention:empty,llm_costs:empty,quality:empty,actions:empty}); const [error,setError]=useState("");
 useEffect(()=>{Promise.all(Object.keys(data).map(async k=>[k,await load(k)])).then(x=>setData(Object.fromEntries(x))).catch(e=>setError(e.message))},[]);
 const period="March–August 2026"; const ch=data.channels.rows||[], f=data.funnel.rows||[], rev=data.revenue_monthly.rows||[], daily=(data.daily_trend.rows||[]).filter(x=>String(x.day||"").slice(0,7)!="2026-09"), llm=data.llm_costs.rows||[];
 const kpis=useMemo(()=>({signups:ch.reduce((s,x)=>s+Number(x.signups||0),0),paid:f.reduce((s,x)=>s+Number(x.payment_success||0),0),net:rev.reduce((s,x)=>s+Number(x.net_revenue_inr||0),0),refund:rev.reduce((s,x)=>s+Number(x.refunded_inr||0),0)}),[ch,f,rev]);
 return <div className="app"><header className="topbar"><div><div className="eyebrow">BUSINESS ANALYTICS</div><h1>Saarthi</h1><p>Funnel, revenue, acquisition channels and retention</p></div><div className="source-badge"><CheckCircle2 size={16}/> BigQuery result exports</div></header>
 <nav className="tabs"><button className={tab==="performance"?"active":""} onClick={()=>setTab("performance")}><BarChart3 size={17}/> Business performance</button><button className={tab==="actions"?"active":""} onClick={()=>setTab("actions")}><ArrowRight size={17}/> What I'd do about it</button></nav>
 {error&&<div className="error"><AlertTriangle size={18}/> {error}</div>}
 {tab==="performance"?<main><div className="hero-row"><div><h2 className="page-title">Business performance</h2><p className="page-subtitle">Every displayed number is from a supplied BigQuery query result.</p></div><div className="period-pill">{period}</div></div>
 <div className="kpi-grid"><Kpi icon={Users} label="Signups" value={number(kpis.signups)}/><Kpi icon={CheckCircle2} label="Payment-success users" value={number(kpis.paid)}/><Kpi icon={IndianRupee} label="Net revenue" value={money(kpis.net)}/><Kpi icon={WalletCards} label="Refunds" value={money(kpis.refund)}/></div>
 <Section title="Conversion funnel by acquisition campaign" period={period}>{f.length?<div className="table-wrap"><table><thead><tr><th>Campaign</th><th>Chat started</th><th>Profile completed</th><th>Paywall</th><th>Payment initiated</th><th>Payment success</th><th>Start → paid</th></tr></thead><tbody>{f.map(r=><tr key={r.utm_campaign}><td className="strong">{r.utm_campaign}</td><td>{number(r.chat_started)}</td><td>{number(r.profile_completed)}</td><td>{number(r.paywall_shown)}</td><td>{number(r.payment_initiated)}</td><td>{number(r.payment_success)}</td><td>{r.overall_conv_pct}%</td></tr>)}</tbody></table></div>:<Empty/>}</Section>
 <Section title="Daily spend, signups and revenue" period={period}>{daily.length?<div className="chart"><ResponsiveContainer width="100%" height={320}><LineChart data={daily}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="day" hide/><YAxis/><Tooltip/><Line type="monotone" dataKey="spend_inr" name="Spend ₹"/><Line type="monotone" dataKey="revenue_inr" name="Revenue ₹"/></LineChart></ResponsiveContainer></div>:<Empty/>}</Section>
 <Section title="Acquisition campaigns: spend, CAC and paying users" period={period}>{ch.length?<div className="table-wrap"><table><thead><tr><th>Campaign</th><th>Spend</th><th>Signups</th><th>Paying users</th><th>CAC / signup</th><th>CAC / paying user</th></tr></thead><tbody>{ch.map(r=><tr key={r.utm_campaign}><td className="strong">{r.utm_campaign}</td><td>{money(r.spend_inr)}</td><td>{number(r.signups)}</td><td>{number(r.paying_users)}</td><td>{money(r.cac_per_signup_inr)}</td><td>{money(r.cac_per_paying_user_inr)}</td></tr>)}</tbody></table></div>:<Empty/>}</Section>
 <Section title="Net revenue and refunds by acquisition campaign" period={period}>{rev.length?<div className="table-wrap"><table><thead><tr><th>Campaign</th><th>Gross revenue</th><th>Refunds</th><th>Net revenue</th></tr></thead><tbody>{rev.map(r=><tr key={r.utm_campaign}><td className="strong">{r.utm_campaign}</td><td>{money(r.gross_revenue_inr)}</td><td>{money(r.refunded_inr)}</td><td>{money(r.net_revenue_inr)}</td></tr>)}</tbody></table></div>:<Empty/>}</Section>
 <Section title="LLM usage cost by acquisition campaign" period={period}>{llm.length?<div className="table-wrap"><table><thead><tr><th>Campaign</th><th>Users with cost</th><th>Total cost USD</th><th>Avg cost/session USD</th></tr></thead><tbody>{llm.map(r=><tr key={r.utm_campaign}><td className="strong">{r.utm_campaign}</td><td>{number(r.users_with_llm_cost)}</td><td>${Number(r.total_llm_cost_usd).toFixed(2)}</td><td>${Number(r.avg_cost_per_session_usd).toFixed(4)}</td></tr>)}</tbody></table></div>:<Empty/>}</Section>
 <Section title="Retention by acquisition cohort" period={period}><Empty text="Retention result has not been exported yet. No retention rate is inferred; this is a known dashboard gap."/></Section>
 <Section title="Data quality and limitations" period={period}><div className="quality-grid">{(data.quality.rows||[]).map((r,i)=><div className="quality" key={i}><AlertTriangle size={17}/><div><strong>{r.issue}</strong><p>{r.detail}</p></div></div>)}</div></Section>
 </main>:<main><div className="hero-row"><div><h2 className="page-title">What I'd do about it</h2><p className="page-subtitle">Scenario-based recommendations tied to the supplied BigQuery outputs.</p></div></div>{(data.actions.rows||[]).slice(0,3).map((a,i)=><article className="action-card" key={i}><div className="action-number">{i+1}</div><div><h3>{a.recommendation}</h3><div className="action-grid"><div><span>Evidence</span><strong>{a.number}</strong><p>{a.source_table}</p></div><div><span>Potential value</span><strong>{a.value_if_works}</strong><p>{a.arithmetic}</p></div><div><span>Would need to be true</span><strong>{a.condition}</strong></div><div><span>Assumption / limitation</span><strong>{a.assumption}</strong></div></div></div></article>)}<div className="do-not"><h3>What I would not do</h3><p>I would not scale a campaign based on signup volume alone, and I would not claim retention or LLM cost in INR without the required cohort result or an FX assumption.</p></div></main>}
 <footer>Analysis period: {period} · Source: BigQuery query results · Saarthi assessment dashboard</footer></div>}
function Kpi({icon:Icon,label,value}){return <div className="kpi"><div className="kpi-icon"><Icon size={18}/></div><div><div className="kpi-label">{label}</div><div className="kpi-value">{value}</div></div></div>}
export default App;
